name: Build OpenWrt (Official Source)

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout OpenWrt Source
      uses: actions/checkout@v3

    - name: Set up Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext libncurses-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget

    - name: Update & Install Feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load Custom Configuration (.config)
      run: |
        ls -al .config || echo "No Config file found"
        cp .config .config.backup
        make defconfig

    - name: Build OpenWrt (Multi-threaded)
      run: |
        make -j$(nproc) || make -j1 V=s

    - name: Upload Firmware to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: OpenWrt-Firmware
        path: bin/targets/
