name: Build OpenWrt

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout OpenWrt Source
      uses: actions/checkout@v3

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext libncurses-dev libssl-dev \
          rsync unzip zlib1g-dev file wget \
          python3-setuptools python3-pip

    - name: Update & Install Feeds
      run: |
        ./scripts/feeds update packages
        ./scripts/feeds install python3-netifaces-src
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load Custom Configuration (.config)
      run: |
        make defconfig

    - name: Build OpenWrt
      run: |
        make -j$(nproc) || make -j1 V=s

    - name: Upload Firmware to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-Firmware
        path: bin/targets/
